[package]
name = "uet-clip"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
uet-core.workspace = true
url.workspace = true
arboard = { version = "3", default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
objc2-app-kit = { version = "0.3", default-features = false, features = ["std", "NSPasteboard"] }
